name: Sync main branch to client-1 branch

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch changes
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Check if client-1 branch is up to date
        run: |
          if [[ "$(git fetch origin && git status -b)" =~ "Your branch is up to date with 'origin/main'" ]]; then
            exit 0
          fi

      - name: Set up client-1 branch
        run: |
          git checkout -b client-1

      - name: Merge changes from main branch
        if: always()
        run: git merge main

      - name: Push changes to client-1 branch
        if: always()
        run: git push -u origin client-1
