name: Overwrite client-1 branch

on:
  push:
    branches:
      - main

jobs:
  overwrite:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout client-1 branch
      run: |
        git checkout client-1

    - name: Fetch the latest changes from the main branch
      run: |
        git fetch origin main

    - name: Reset the client-1 branch to match the main branch
      run: |
        git reset --hard origin/main

    - name: Force push the client-1 branch to the remote repository
      run: |
        git push origin client-1 --force
