name: Sync to client-1 branch

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Create or update client-1 branch
      run: |
        # Create or update the client-1 branch
        git checkout -B client-1
        git push origin client-1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Merge client-1 branches
      run: |
        # Fetch the latest changes from the remote client-1 branch
        git fetch origin client-1

        # Identify a common ancestor commit (commit_hash) between local and remote
        # Then, perform a merge
        git merge commit_hash

        # Resolve any conflicts and commit the merge
        git commit -m "Merged changes from client-1 branch"

        # Push the merged changes to the remote client-1 branch
        git push origin client-1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
