name: Sync to client-1 branch

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Create or update client-1 branch
      run: |
        # Switch to the client-1 branch
        git checkout client-1

        # Merge changes from the main branch into client-1
        git merge main

        # Push the changes to the client-1 branch
        git push origin client-1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
